Lint Drupal's PHP coding standards
chapter-three/next-drupal pull request #552
Opened 2023-10-15 05:23 UTC by JohnAlbin

This pull request is for: (mark with an "x")
- [ ] `examples/*`
- [x] `modules/next`
- [ ] `packages/next-drupal`
- [ ] `starters/basic-starter`
- [ ] `starters/graphql-starter`
- [ ] Other

GitHub Issue: # 551

## Describe your changes

Instead of only linting some of code sniffs, lint all of Drupal's PHP coding standards.

2023-10-17 16:30 UTC, robdecker requested changes

2023-10-17 16:30 UTC, robdecker commented on modules/next/src/Plugin/Next/SiteResolver/SiteSelector.php
> +// @codingStandardsIgnoreStart
Same as above.

2023-10-17 18:25 UTC, JohnAlbin commented on modules/next/src/Plugin/Next/SiteResolver/EntityReferenceField.php
> +// @codingStandardsIgnoreStart
Can do. I should point out that the added white space and the added `*` will become part of the annotation text. https://stackoverflow.com/questions/23438467/split-long-annotation-string-across-multiple-lines-in-a-docblock

2023-10-19 00:02 UTC, robdecker approved these changes
LGTM 👍

2023-10-19 08:04 UTC, merged