feat(next-drupal, starters-*) - Add Next 15 support
chapter-three/next-drupal pull request #824
Opened 2024-12-06 10:21 UTC by yobottehg

This pull request is for: (mark with an "x")

- [ ] `examples/*`
- [ ] `modules/next`
- [x] `packages/next-drupal`
- [x] `starters/basic-starter`
- [x] `starters/graphql-starter`
- [x] `starters/pages-starter`
- [ ] Other

GitHub Issue: #811 

## Describe your changes

- Added support for Next.js 15 in next-drupal module
- Removed support for Next.js 13 and 14 because of incompabilities in how async requests are handled. 
- Adjustes all starters to use Next.js 15
- 

After reading through https://nextjs.org/docs/app/building-your-application/upgrading/version-15#async-request-apis-breaking-change I decided to not add the "workaround" to also support Next.js 14 because:

1. Pages router is not affected and can totally easily be upgraded to Next.js 15
2. App router support for next-drupal is still in beta so we can do these kind of breaking changes.
3. Documentation says "Temporarily allow ..." Whatever that means! So better be safe.

2025-01-17 22:53 UTC, backlineint requested changes
Thanks for the contribution @yobottehg! Provided some inline feedback, but this is most of the way there from my perspective.

2025-01-17 22:53 UTC, backlineint commented on starters/pages-starter/components/drupal/ArticleTeaser.tsx
Unless I'm missing something, the link related change here seems like something that is beyond the scope of Next 15 support. The docs imply that prefetch still defaults to true, which would make this a functional change https://nextjs.org/docs/pages/api-reference/components/link#prefetch

2025-01-17 23:02 UTC, backlineint commented on packages/next-drupal/package.json
> +    "next": "^15.0.4",
From my testing it does look like the changes here (mainly the draft mode changes) will work on both 14 and 15.

2025-01-20 08:12 UTC, yobottehg commented on CONTRIBUTING.md
> +Due to the current CI/CD setup it is not possible to run the tests locally.
As this will never be a full e2e test in jest I would just mock all the Drupal responses. For e2e tests I think a cypress / playwright setup would be better suited.

2025-01-20 08:13 UTC, yobottehg commented on packages/next-drupal/tests/draft/draft.test.ts
I had that in the beginning but something is odd in the tests when I re-use these objects from draftMode / cookies which lead the tests to failures. I changed the style to make the test failures clear

2025-01-20 08:14 UTC, yobottehg commented on starters/pages-starter/components/drupal/ArticleTeaser.tsx
I changed that because it had problems in Next.js 15.0.4 which are not an issue anymore in 15.1.x - But from my perspective It is not worth it to maintain code like this over the time. A comment in the docs would be enough.

2025-01-23 16:09 UTC, backlineint commented on packages/next-drupal/tests/draft/draft.test.ts
Thanks for clarifying. Don't understand why that workaround is necessary, but it is called out clearly in the tests and they pass, so I think it is reasonable to move forward with this.

2025-01-23 16:14 UTC, backlineint commented on starters/pages-starter/components/drupal/ArticleTeaser.tsx
I see the component itself restored in the current diff, but it doesn't look like it is being used. I'll comment inline.

> But from my perspective It is not worth it to maintain code like this over the time. A comment in the docs would be enough.

Agree with you in general, just think it belongs outside of the scope of this issue.

2025-01-23 16:34 UTC, backlineint requested changes
Just about there! From my perspective this just needs to go back to using the custom link component (see comments inline) and also needs to have a merge conflict resolved, and then it is good to go.

2025-01-23 16:34 UTC, backlineint commented on starters/pages-starter/components/drupal/ArticleTeaser.tsx
I think the changes here also need to be reverted to go back to the custom Link component.

2025-01-23 16:34 UTC, backlineint commented on starters/pages-starter/components/navigation/HeaderNav.tsx
> +import Link from "next/link"
I think the changes here also need to be reverted to go back to the custom Link component.

2025-01-23 17:30 UTC, robdecker requested changes

2025-01-24 07:30 UTC, yobottehg commented
All requested changes addressed

2025-01-27 20:24 UTC, backlineint approved these changes
Thanks for all the work on this @yobottehg !

2025-01-27 20:27 UTC, merged